### PR TITLE
Force all transaction ID in the key to be 32 bytes long

### LINKED ISSUE #53: Ordering for ledger.list is incorrect
Ran this command to get list of transactions but ordering is off:
`many message --server http://localhost:8000 ledger.list '{1:2}'`

### PR DESCRIPTION
**Pull request by hansl**
Fixes #53

### CODE REVIEW

File: src/many-ledger/src/storage.rs [hunk 1]
```diff
@@ -15,13 +15,26 @@ pub(crate) const TRANSACTIONS_ROOT: &[u8] = b"/transactions/";
...
 /// Returns the key for the persistent kv-store.
 pub(crate) fn key_for_account(id: &Identity, symbol: &Symbol) -> Vec<u8> {
     format!("/balances/{}/{}", id, symbol).into_bytes()
 }
 
+/// Returns the storage key for a transaction in the kv-store.
 pub(crate) fn key_for_transaction(id: TransactionId) -> Vec<u8> {
-    vec![TRANSACTIONS_ROOT.to_vec(), id.into()].concat()
+    let mut id: Vec<u8> = id.0.into();
+    id.extend(
```
Comment (fmorency) [inline src/many-ledger/src/storage.rs:30]: Don't you want to prepend `0`s here?

**Review by fmorency — COMMENTED** [review]
Thanks! Small question.

nit: Add a test!

File: src/many-ledger/src/storage.rs (hunk 1 above)
Comment (hansl) [reply src/many-ledger/src/storage.rs:30]: hum... you right. fixed

File: src/many-ledger/src/storage.rs [hunk 2]
```diff
@@ -17,24 +17,18 @@ const HEIGHT_TXID_SHIFT: u64 = 32;
...
-        std::iter::repeat(0).take(
-            TRANSACTION_ID_KEY_SIZE
-                .checked_sub(id.len())
-                .expect("Transaction ID larger than max size."),
-        ),
-    );
-    vec![TRANSACTIONS_ROOT.to_vec(), id].concat()
+pub(super) fn key_for_transaction(id: TransactionId) -> Vec<u8> {
+    let mut exp_id = [0u8; TRANSACTION_ID_KEY_SIZE_IN_BYTES];
+    exp_id[(TRANSACTION_ID_KEY_SIZE_IN_BYTES - id.0.len())..].copy_from_slice(&id.0);
```
Comment (fmorency) [inline src/many-ledger/src/storage.rs:30]: I **think** this can be abused via the LedgerStorage iterator right now, i.e. this can panic with an overflow.

Ex:
```
    storage
        .iter(
            CborRange {
                start: Bound::Unbounded,
                end: Bound::Included(TransactionId::from(vec![1u8; 33])),
            },
            SortOrder::Ascending,
        )
        .all(|_| true);
```

WDYT?

**Comment by hansl** [comment]
> BTW, you pushed your branch in the main repo, and not to your fork :)

I used GitHub inline editor. I wasn't expecting 7 comments and 2 full days.

File: src/many-ledger/src/storage.rs (hunk 2 above)
Comment (hansl) [reply src/many-ledger/src/storage.rs:30]: Yes, we know TransactionId with greater than 32 bytes will panic.

Comment (hansl) [reply src/many-ledger/src/storage.rs:30]: I can't return a result. This needs to either panic or succeeds. Now there can be user entry so what I'll do is cut it instead of panicking.

**Comment by hansl** [comment]
@fmorency PTAL

**Review by fmorency — APPROVED** [review]
